feat: add navbar
danielkull/capp pull request #93
Opened 2023-07-05 00:09 UTC by StefanH87

- add componente - NavBar.vue
- add icons
- add navbar style
- add menue list
- add btn active
- set in MainPageView
- add cards - Placeholder for filling

![image](https://github.com/danielkull/capp/assets/120994075/d01d66a7-8f56-4518-93e1-8c74fdb2022a)

![image](https://github.com/danielkull/capp/assets/120994075/4512fd97-4b52-4a8e-8b4b-ef498dfaf4e1)

![image](https://github.com/danielkull/capp/assets/120994075/34abe72e-9394-4776-ae47-347a89e01c49)

2023-07-05 08:42 UTC, kerstin-m commented on src/styles/color-properties.css
Schau mal, Zeile 60 hast Du  --bg-lis-surface geschrieben, gemeint hast Du aber wahrscheinlich --bg-list-surface, oder?

2023-07-05 08:47 UTC, kerstin-m requested changes
Siehe Tippie Zeile 60:-)

2023-07-05 20:05 UTC, StefanH87 commented
ja hatte ich gesesehen aber im code selbst direkt einfgüft also gehts erst mal so, korrigiere das wenn ich ejnochmal drüber gehe mit den properties

2023-07-05 20:11 UTC, StefanH87 commented on src/styles/color-properties.css
tippfehler erst mal lassen , ist o als CP auch in den Elementen, wird später korrigiert

2023-07-06 04:53 UTC, kerstin-m approved these changes

2023-07-06 04:53 UTC, merged